name: post-models-report
on:
  workflow_dispatch: {}
  schedule:
    # 毎日 00:00 UTC（JST 09:00）
    - cron: "0 0 * * *"

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci || npm i

      - name: Post OpenAI models report
        run: node scripts/post-models-report.mjs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
